Fraunhofer-AISEC/cmc

- .github/workflows/build.yml
> Added GitHub Actions

- attestationreport/attestationreport.go
- cmcd/main.go
The attestationreport module can now also be used by
modules other than the cmcd which do not require
certain certificate roles to be checked.
> attestationreport: Make certificate roles optional

- cmcd/main.go
- go.mod
- go.sum
watch the cmcd metadata directory for file system
changes and update metadata on change.
> Implemented file system watcher

- cmcd/main.go
> cmcd: Improved error handling when loading metadata

- .gitignore
- README.md
- attestationreport/attestationreport.go
- attestedtls/backend.go
- attestedtls/dialer.go
- attestedtls/listener.go
- attestedtls/tpmkey.go
- cmcd/main.go
- example-setup/cmcd-conf.json
- provserver/server.go
- testclient/testclient.go
- testconnector/Makefile
- testconnector/testconnector.go
- tpmdriver/tpmdriver.go
- Attested TLS Library: wrapper around crypto/tls which performs additional remote attestation steps during connection establishment
- Test connector: new  component that acts as a server listening for incoming connections using the attested TLS library
- Test client extended: new functionality allows to connect to test connector using attested TLS
- General: added support for Elliptic Curve keys and different key configurations
> Attestedtls

- provclient/provclient.go
Prevents obsolete files from being parsed during
cmcd initialization
> provclient: Remove metadata before metadata update

- attestationreport/attestationreport.go
Nonces mismatch error messages improved
> attestationreport: Better error message

- .github/workflows/build.yml
> Include go vet in ci/cd pipeline

- attestationreport/attestationreport.go
- attestationreport/validationreport.go
* removed error messages with "\n" by introducing ResultMulti with []string for details
* introduced setFalse and setFalseMulti function to reduce duplicate code
> validation report: fixed error messages and simplified code

- attestationreport/attestationreport.go
Reduced complexity of Verify function
> attestationreport: Refactoring

- testclient/testclient.go
- testconnector/testconnector.go
Updated listening address/port of testconnector so it can be reached from other platforms as well
> testconnector+client: new listener address/port

- provserver/server.go
The AMD KDF server allows requests only every ten seconds.
Only allow one parallel requests in the provserver at once
and cache the certificates to avoid getting blocked when
several VMs try to fetch certificates in parallel.
> provserver: Implemented caching and sync for VCEK

- provserver/server.go
> provserver: Implemented option for offline VCEK caching

- provserver/server.go
> provserver: store and load cached VCEKS in DER format.

- attestedtls/backend.go
- attestedtls/listener.go
- testclient/testclient.go
> Unified timeouts

- .github/workflows/build.yml
- attestationreport/snp.go
- attestationreport/tpm.go
- attestationreport/validationreport.go
- attestedtls/attestation.go
- doc/platform-configuration.md
- go.mod
- go.sum
> Added misspell and ineffassign tools, fixed some typos.

- provserver/server.go
> Updated dependencies, added comments

- testclient/testclient.go
> testclient: error message if saving files fails

- attestationreport/attestationreport.go
- attestationreport/cbor.go
- attestationreport/json.go
- attestationreport/validationreport.go
> attestationreport: renamed jws result to generic result

- example-setup/prov-server-conf.json
- provserver/server.go
- tools/signing-tool/main.go
- tpmdriver/tpmdriver.go
> provserver: refactoring for flexible PKIs

- provserver/server.go
> provserver: error handling

- README.md
- attestationreport/attestationreport.go
- attestationreport/attestationreport_test.go
- attestationreport/iat.go
- attestationreport/iat_test.go
- attestationreport/snp.go
- attestationreport/snp_test.go
- attestationreport/tpm.go
- attestationreport/tpm_test.go
- attestationreport/validationreport.go
- example-setup/metadata-raw/app.manifest.json
- example-setup/metadata-raw/os.manifest.json
- example-setup/metadata-raw/rtm.manifest.json
- example-setup/setup-full-simple
- example-setup/update-full-simple
- tpmdriver/tpmdriver.go
> refactoring: renamed Verifications to ReferenceValues

- provserver/server.go
- snpdriver/snpdriver.go
- swdriver/swdriver.go
- tpmdriver/tpmdriver.go
Introduced versions for protocol between drivers and server to detect incompatibilities.
> provserver: introduced protocol versions

- cmcd/main.go
- swdriver/swdriver.go
> swdriver: simplified setup

- tools/signing-tool/json.go
- tools/signing-tool/main.go
> Ed25519 support

- README.md
- example-setup/setup-full-simple
> Updated README

- testconnector/testconnector.go
> testconnector: specify address

- cmcd/main.go
- swdriver/swdriver.go
> swdriver: store ca to file system

- example-setup/metadata-raw/device.config.json
> example-setup: fixed example device config

- attestationreport/iat.go
- attestationreport/snp.go
- attestationreport/tpm.go
- attestationreport/tpm_test.go
- attestationreport/validationreport.go
- testtool/internal.go
Include the measurements and reference values in
the validation report to enable analysis of failed attestations.
> attestationreport: More verbose validationreport

- README.md
- example-setup/est-server-conf.json
- example-setup/testtool-config.json
- testtool/config.go
- testtool/hub.go
- testtool/internal.go
- tpmdriver/tpmdriver.go
This PR extends the testtool to support regularly dialing multiple addresses.
> Monitoring

- attestedtls/attestation.go
- attestedtls/config.go
- attestedtls/dialer.go
- attestedtls/key.go
- attestedtls/listener.go
- testtool/config.go
- testtool/internal.go
> aTLS: make attestation mutual, server only, or client only

- attestationreport/attestationreport.go
- attestationreport/bioseventdata.go
- attestationreport/tpm.go
- attestationreport/validationreport.go
- cmc/cmc.go
- cmcd/config.go
- doc/configuration.md
- testtool/config.go
- testtool/libapi.go
- tpmdriver/bioseventlog.go
- tpmdriver/bioseventlog_test.go
- tpmdriver/tpmdriver.go
implementation: bios event data parsing
> tpm eventlog (event data) parsing

- swdriver/swdriver.go
- tpmdriver/tpmdriver.go
> swdriver: small fix to generate measurement even if no containers were
